# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: dbcm7ilmjj7stv
  host: ec2-54-235-125-172.compute-1.amazonaws.com
  username: lrrcmlodpqnxcz
  password: teievXkfti-RCPsTpikiGFcLuA
  timeout: 5000

testing:
  adapter: postgresql
  database: flux
  host: localhost
  username: postgres
  password: postgres

staging:
  adapter: postgresql
  database: dbcm7ilmjj7stv
  host: ec2-54-235-125-172.compute-1.amazonaws.com
  username: lrrcmlodpqnxcz
  password: teievXkfti-RCPsTpikiGFcLuA
  timeout: 5000

production:
  adapter: postgresql
  database: flux
  host: flux.cusoasn3tavc.us-west-2.rds.amazonaws.com
  username: flux
  password: design5678
  port: 5432
  timeout: 5000
