# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: flux
  username: postgres
  password: postgres
  host: localhost

staging:
  adapter: postgresql
  database: flux
  host: 54.221.254.230
  username: postgres
  timeout: 5000

test:
  adapter: postgresql
  database: flux
  host: 54.221.222.71
  username: postgres
  timeout: 5000
