# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: flux
  host: localhost
  username: postgres
  password: postgres

staging:
  adapter: postgresql
  database: flux
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000

staging2:
  adapter: postgresql
  database: flux
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000
