# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: flux2
  host: 192.168.0.65
  username: postgres
  password: postgres
  timeout: 5000

staging:
  adapter: postgresql
  database: flux2
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000
